services:
  - type: web
    name: devc-api
    runtime: docker
    plan: starter
    healthCheckPath: /api/v1/health/ready
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: 3001
      - key: APP_NAME
        value: "Devc NestJS REST API"
      - key: API_PREFIX
        value: "api/v1"
      - key: LOG_LEVEL
        value: "info"
      - key: SWAGGER_ENABLED
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: devc-api-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

databases:
  - name: devc-api-db
    plan: starter
